//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 06:45:41 PM EET 
//


package ch.swissbilling.framework.einvoice.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillHeaderType", propOrder = {
    "documentType",
    "documentSubType",
    "documentID",
    "documentReference",
    "documentDate",
    "senderParty",
    "receiverParty",
    "invoiceReceivingParty",
    "deliveryPlace",
    "achievementDate",
    "currency",
    "accountAssignment",
    "fixedReference",
    "language",
    "paymentInformation",
    "freeText"
})
@XmlSeeAlso({
    ch.swissbilling.framework.einvoice.models.BillType.Header.class
})
public class BillHeaderType {

    @XmlElement(name = "DocumentType", required = true)
    protected String documentType;
    @XmlElement(name = "DocumentSubType")
    protected String documentSubType;
    @XmlElement(name = "DocumentID", required = true)
    protected String documentID;
    @XmlElement(name = "DocumentReference")
    protected List<Reference> documentReference;
    @XmlElement(name = "DocumentDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar documentDate;
    @XmlElement(name = "SenderParty", required = true)
    protected BillHeaderType.SenderParty senderParty;
    @XmlElement(name = "ReceiverParty", required = true)
    protected BillHeaderType.ReceiverParty receiverParty;
    @XmlElement(name = "InvoiceReceivingParty")
    protected PartyType invoiceReceivingParty;
    @XmlElement(name = "DeliveryPlace")
    protected PartyType deliveryPlace;
    @XmlElement(name = "AchievementDate")
    protected AchievementDateType achievementDate;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "AccountAssignment")
    protected AccountAssignmentType accountAssignment;
    @XmlElement(name = "FixedReference")
    protected List<FixedReference> fixedReference;
    @XmlElement(name = "Language", required = true)
    protected String language;
    @XmlElement(name = "PaymentInformation", required = true)
    protected BillHeaderType.PaymentInformation paymentInformation;
    @XmlElement(name = "FreeText")
    protected List<String> freeText;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentSubType() {
        return documentSubType;
    }

    /**
     * Sets the value of the documentSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentSubType(String value) {
        this.documentSubType = value;
    }

    /**
     * Gets the value of the documentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the documentReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getDocumentReference() {
        if (documentReference == null) {
            documentReference = new ArrayList<Reference>();
        }
        return this.documentReference;
    }

    /**
     * Gets the value of the documentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocumentDate(XMLGregorianCalendar value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the senderParty property.
     * 
     * @return
     *     possible object is
     *     {@link BillHeaderType.SenderParty }
     *     
     */
    public BillHeaderType.SenderParty getSenderParty() {
        return senderParty;
    }

    /**
     * Sets the value of the senderParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillHeaderType.SenderParty }
     *     
     */
    public void setSenderParty(BillHeaderType.SenderParty value) {
        this.senderParty = value;
    }

    /**
     * Gets the value of the receiverParty property.
     * 
     * @return
     *     possible object is
     *     {@link BillHeaderType.ReceiverParty }
     *     
     */
    public BillHeaderType.ReceiverParty getReceiverParty() {
        return receiverParty;
    }

    /**
     * Sets the value of the receiverParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillHeaderType.ReceiverParty }
     *     
     */
    public void setReceiverParty(BillHeaderType.ReceiverParty value) {
        this.receiverParty = value;
    }

    /**
     * Gets the value of the invoiceReceivingParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getInvoiceReceivingParty() {
        return invoiceReceivingParty;
    }

    /**
     * Sets the value of the invoiceReceivingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setInvoiceReceivingParty(PartyType value) {
        this.invoiceReceivingParty = value;
    }

    /**
     * Gets the value of the deliveryPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getDeliveryPlace() {
        return deliveryPlace;
    }

    /**
     * Sets the value of the deliveryPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setDeliveryPlace(PartyType value) {
        this.deliveryPlace = value;
    }

    /**
     * Gets the value of the achievementDate property.
     * 
     * @return
     *     possible object is
     *     {@link AchievementDateType }
     *     
     */
    public AchievementDateType getAchievementDate() {
        return achievementDate;
    }

    /**
     * Sets the value of the achievementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AchievementDateType }
     *     
     */
    public void setAchievementDate(AchievementDateType value) {
        this.achievementDate = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the accountAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link AccountAssignmentType }
     *     
     */
    public AccountAssignmentType getAccountAssignment() {
        return accountAssignment;
    }

    /**
     * Sets the value of the accountAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountAssignmentType }
     *     
     */
    public void setAccountAssignment(AccountAssignmentType value) {
        this.accountAssignment = value;
    }

    /**
     * Gets the value of the fixedReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixedReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixedReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FixedReference }
     * 
     * 
     */
    public List<FixedReference> getFixedReference() {
        if (fixedReference == null) {
            fixedReference = new ArrayList<FixedReference>();
        }
        return this.fixedReference;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the paymentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BillHeaderType.PaymentInformation }
     *     
     */
    public BillHeaderType.PaymentInformation getPaymentInformation() {
        return paymentInformation;
    }

    /**
     * Sets the value of the paymentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillHeaderType.PaymentInformation }
     *     
     */
    public void setPaymentInformation(BillHeaderType.PaymentInformation value) {
        this.paymentInformation = value;
    }

    /**
     * Gets the value of the freeText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freeText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreeText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFreeText() {
        if (freeText == null) {
            freeText = new ArrayList<String>();
        }
        return this.freeText;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentDueDate",
        "paymentType",
        "fixAmount",
        "esr",
        "iban",
        "instalments"
    })
    public static class PaymentInformation {

        @XmlElement(name = "PaymentDueDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar paymentDueDate;
        @XmlElement(name = "PaymentType", required = true)
        protected String paymentType;
        @XmlElement(required = true)
        protected String fixAmount;
        @XmlElement(name = "ESR")
        protected BillHeaderType.PaymentInformation.ESR esr;
        @XmlElement(name = "IBAN")
        protected BillHeaderType.PaymentInformation.IBAN iban;
        @XmlElement(name = "Instalments")
        protected BillHeaderType.PaymentInformation.Instalments instalments;

        /**
         * Gets the value of the paymentDueDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPaymentDueDate() {
            return paymentDueDate;
        }

        /**
         * Sets the value of the paymentDueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPaymentDueDate(XMLGregorianCalendar value) {
            this.paymentDueDate = value;
        }

        /**
         * Gets the value of the paymentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentType() {
            return paymentType;
        }

        /**
         * Sets the value of the paymentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentType(String value) {
            this.paymentType = value;
        }

        /**
         * Gets the value of the fixAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFixAmount() {
            return fixAmount;
        }

        /**
         * Sets the value of the fixAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFixAmount(String value) {
            this.fixAmount = value;
        }

        /**
         * Gets the value of the esr property.
         * 
         * @return
         *     possible object is
         *     {@link BillHeaderType.PaymentInformation.ESR }
         *     
         */
        public BillHeaderType.PaymentInformation.ESR getESR() {
            return esr;
        }

        /**
         * Sets the value of the esr property.
         * 
         * @param value
         *     allowed object is
         *     {@link BillHeaderType.PaymentInformation.ESR }
         *     
         */
        public void setESR(BillHeaderType.PaymentInformation.ESR value) {
            this.esr = value;
        }

        /**
         * Gets the value of the iban property.
         * 
         * @return
         *     possible object is
         *     {@link BillHeaderType.PaymentInformation.IBAN }
         *     
         */
        public BillHeaderType.PaymentInformation.IBAN getIBAN() {
            return iban;
        }

        /**
         * Sets the value of the iban property.
         * 
         * @param value
         *     allowed object is
         *     {@link BillHeaderType.PaymentInformation.IBAN }
         *     
         */
        public void setIBAN(BillHeaderType.PaymentInformation.IBAN value) {
            this.iban = value;
        }

        /**
         * Gets the value of the instalments property.
         * 
         * @return
         *     possible object is
         *     {@link BillHeaderType.PaymentInformation.Instalments }
         *     
         */
        public BillHeaderType.PaymentInformation.Instalments getInstalments() {
            return instalments;
        }

        /**
         * Sets the value of the instalments property.
         * 
         * @param value
         *     allowed object is
         *     {@link BillHeaderType.PaymentInformation.Instalments }
         *     
         */
        public void setInstalments(BillHeaderType.PaymentInformation.Instalments value) {
            this.instalments = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "esrCustomerNumber",
            "esrReferenceNumber"
        })
        public static class ESR {

            @XmlElement(name = "ESRCustomerNumber", required = true)
            protected String esrCustomerNumber;
            @XmlElement(name = "ESRReferenceNumber", required = true)
            protected String esrReferenceNumber;

            /**
             * Gets the value of the esrCustomerNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getESRCustomerNumber() {
                return esrCustomerNumber;
            }

            /**
             * Sets the value of the esrCustomerNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setESRCustomerNumber(String value) {
                this.esrCustomerNumber = value;
            }

            /**
             * Gets the value of the esrReferenceNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getESRReferenceNumber() {
                return esrReferenceNumber;
            }

            /**
             * Sets the value of the esrReferenceNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setESRReferenceNumber(String value) {
                this.esrReferenceNumber = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bic",
            "bankName",
            "iban",
            "creditorName",
            "creditorReference",
            "chargingOption"
        })
        public static class IBAN {

            @XmlElement(name = "BIC")
            protected String bic;
            @XmlElement(name = "BankName")
            protected String bankName;
            @XmlElement(name = "IBAN", required = true)
            protected String iban;
            @XmlElement(name = "CreditorName")
            protected String creditorName;
            @XmlElement(name = "CreditorReference")
            protected String creditorReference;
            @XmlElement(name = "ChargingOption")
            protected String chargingOption;

            /**
             * Gets the value of the bic property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBIC() {
                return bic;
            }

            /**
             * Sets the value of the bic property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBIC(String value) {
                this.bic = value;
            }

            /**
             * Gets the value of the bankName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBankName() {
                return bankName;
            }

            /**
             * Sets the value of the bankName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBankName(String value) {
                this.bankName = value;
            }

            /**
             * Gets the value of the iban property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIBAN() {
                return iban;
            }

            /**
             * Sets the value of the iban property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIBAN(String value) {
                this.iban = value;
            }

            /**
             * Gets the value of the creditorName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCreditorName() {
                return creditorName;
            }

            /**
             * Sets the value of the creditorName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCreditorName(String value) {
                this.creditorName = value;
            }

            /**
             * Gets the value of the creditorReference property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCreditorReference() {
                return creditorReference;
            }

            /**
             * Sets the value of the creditorReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCreditorReference(String value) {
                this.creditorReference = value;
            }

            /**
             * Gets the value of the chargingOption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChargingOption() {
                return chargingOption;
            }

            /**
             * Sets the value of the chargingOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargingOption(String value) {
                this.chargingOption = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "instalment"
        })
        public static class Instalments {

            @XmlElement(name = "Instalment", required = true)
            protected List<BillHeaderType.PaymentInformation.Instalments.Instalment> instalment;

            /**
             * Gets the value of the instalment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the instalment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInstalment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BillHeaderType.PaymentInformation.Instalments.Instalment }
             * 
             * 
             */
            public List<BillHeaderType.PaymentInformation.Instalments.Instalment> getInstalment() {
                if (instalment == null) {
                    instalment = new ArrayList<BillHeaderType.PaymentInformation.Instalments.Instalment>();
                }
                return this.instalment;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Instalment
                extends InstalmentType
            {


            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "network",
        "partyType"
    })
    public static class ReceiverParty {

        @XmlElement(name = "Network")
        protected NetworkType network;
        @XmlElement(name = "PartyType", required = true)
        protected PartyType partyType;

        /**
         * Gets the value of the network property.
         * 
         * @return
         *     possible object is
         *     {@link NetworkType }
         *     
         */
        public NetworkType getNetwork() {
            return network;
        }

        /**
         * Sets the value of the network property.
         * 
         * @param value
         *     allowed object is
         *     {@link NetworkType }
         *     
         */
        public void setNetwork(NetworkType value) {
            this.network = value;
        }

        /**
         * Gets the value of the partyType property.
         * 
         * @return
         *     possible object is
         *     {@link PartyType }
         *     
         */
        public PartyType getPartyType() {
            return partyType;
        }

        /**
         * Sets the value of the partyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartyType }
         *     
         */
        public void setPartyType(PartyType value) {
            this.partyType = value;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "network",
        "taxLiability",
        "partyType"
    })
    public static class SenderParty {

        @XmlElement(name = "Network")
        protected NetworkType network;
        @XmlElement(name = "TaxLiability", required = true)
        protected String taxLiability;
        @XmlElement(name = "PartyType", required = true)
        protected PartyType partyType;

        /**
         * Gets the value of the network property.
         * 
         * @return
         *     possible object is
         *     {@link NetworkType }
         *     
         */
        public NetworkType getNetwork() {
            return network;
        }

        /**
         * Sets the value of the network property.
         * 
         * @param value
         *     allowed object is
         *     {@link NetworkType }
         *     
         */
        public void setNetwork(NetworkType value) {
            this.network = value;
        }

        /**
         * Gets the value of the taxLiability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxLiability() {
            return taxLiability;
        }

        /**
         * Sets the value of the taxLiability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxLiability(String value) {
            this.taxLiability = value;
        }

        /**
         * Gets the value of the partyType property.
         * 
         * @return
         *     possible object is
         *     {@link PartyType }
         *     
         */
        public PartyType getPartyType() {
            return partyType;
        }

        /**
         * Sets the value of the partyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartyType }
         *     
         */
        public void setPartyType(PartyType value) {
            this.partyType = value;
        }

    }

}
