//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 06:45:41 PM EET 
//


package ch.swissbilling.framework.einvoice.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillType", propOrder = {
    "header",
    "lineItems",
    "summary"
})
public class BillType {

    @XmlElement(name = "Header", required = true)
    protected BillType.Header header;
    @XmlElement(name = "LineItems", required = true)
    protected BillType.LineItems lineItems;
    @XmlElement(name = "Summary", required = true)
    protected SummaryType summary;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link BillType.Header }
     *     
     */
    public BillType.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillType.Header }
     *     
     */
    public void setHeader(BillType.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the lineItems property.
     * 
     * @return
     *     possible object is
     *     {@link BillType.LineItems }
     *     
     */
    public BillType.LineItems getLineItems() {
        return lineItems;
    }

    /**
     * Sets the value of the lineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillType.LineItems }
     *     
     */
    public void setLineItems(BillType.LineItems value) {
        this.lineItems = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryType }
     *     
     */
    public SummaryType getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryType }
     *     
     */
    public void setSummary(SummaryType value) {
        this.summary = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Header
        extends BillHeaderType
    {


    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lineItem"
    })
    public static class LineItems {

        @XmlElement(name = "LineItem", required = true)
        protected List<LineItemType> lineItem;

        /**
         * Gets the value of the lineItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lineItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLineItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LineItemType }
         * 
         * 
         */
        public List<LineItemType> getLineItem() {
            if (lineItem == null) {
                lineItem = new ArrayList<LineItemType>();
            }
            return this.lineItem;
        }

    }

}
