//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 06:45:41 PM EET 
//


package ch.swissbilling.framework.einvoice.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryType", propOrder = {
    "billerID",
    "eBillAccountID",
    "deliveryID",
    "deliveryDate",
    "transactionID",
    "billDetailsType",
    "urlBillDetails"
})
public class DeliveryType {

    @XmlElement(name = "BillerID")
    protected long billerID;
    protected long eBillAccountID;
    @XmlElement(name = "DeliveryID")
    protected String deliveryID;
    @XmlElement(name = "DeliveryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "TransactionID", required = true)
    protected String transactionID;
    @XmlElement(name = "BillDetailsType", required = true)
    protected String billDetailsType;
    @XmlElementRef(name = "URLBillDetails", type = JAXBElement.class, required = false)
    protected JAXBElement<String> urlBillDetails;

    /**
     * Gets the value of the billerID property.
     * 
     */
    public long getBillerID() {
        return billerID;
    }

    /**
     * Sets the value of the billerID property.
     * 
     */
    public void setBillerID(long value) {
        this.billerID = value;
    }

    /**
     * Gets the value of the eBillAccountID property.
     * 
     */
    public long getEBillAccountID() {
        return eBillAccountID;
    }

    /**
     * Sets the value of the eBillAccountID property.
     * 
     */
    public void setEBillAccountID(long value) {
        this.eBillAccountID = value;
    }

    /**
     * Gets the value of the deliveryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryID() {
        return deliveryID;
    }

    /**
     * Sets the value of the deliveryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryID(String value) {
        this.deliveryID = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the billDetailsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDetailsType() {
        return billDetailsType;
    }

    /**
     * Sets the value of the billDetailsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDetailsType(String value) {
        this.billDetailsType = value;
    }

    /**
     * Gets the value of the urlBillDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getURLBillDetails() {
        return urlBillDetails;
    }

    /**
     * Sets the value of the urlBillDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setURLBillDetails(JAXBElement<String> value) {
        this.urlBillDetails = ((JAXBElement<String> ) value);
    }

}
