//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 06:45:41 PM EET 
//


package ch.swissbilling.framework.einvoice.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _DeliveryTypeURLBillDetails_QNAME = new QName("", "URLBillDetails");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.swissbilling.framework.einvoice.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BillHeaderType.ReceiverParty }
     * 
     */
    public BillHeaderType.ReceiverParty createBillHeaderTypeReceiverParty() {
        return new BillHeaderType.ReceiverParty();
    }

    /**
     * Create an instance of {@link AchievementDateType }
     * 
     */
    public AchievementDateType createAchievementDateType() {
        return new AchievementDateType();
    }

    /**
     * Create an instance of {@link DeliveryType }
     * 
     */
    public DeliveryType createDeliveryType() {
        return new DeliveryType();
    }

    /**
     * Create an instance of {@link AppendixType.Document }
     * 
     */
    public AppendixType.Document createAppendixTypeDocument() {
        return new AppendixType.Document();
    }

    /**
     * Create an instance of {@link BillType.Header }
     * 
     */
    public BillType.Header createBillTypeHeader() {
        return new BillType.Header();
    }

    /**
     * Create an instance of {@link BillType }
     * 
     */
    public BillType createBillType() {
        return new BillType();
    }

    /**
     * Create an instance of {@link BillHeaderType.PaymentInformation.Instalments.Instalment }
     * 
     */
    public BillHeaderType.PaymentInformation.Instalments.Instalment createBillHeaderTypePaymentInformationInstalmentsInstalment() {
        return new BillHeaderType.PaymentInformation.Instalments.Instalment();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link BillHeaderType.PaymentInformation }
     * 
     */
    public BillHeaderType.PaymentInformation createBillHeaderTypePaymentInformation() {
        return new BillHeaderType.PaymentInformation();
    }

    /**
     * Create an instance of {@link LineItemType.AllowanceAndCharge }
     * 
     */
    public LineItemType.AllowanceAndCharge createLineItemTypeAllowanceAndCharge() {
        return new LineItemType.AllowanceAndCharge();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link AppendixType }
     * 
     */
    public AppendixType createAppendixType() {
        return new AppendixType();
    }

    /**
     * Create an instance of {@link BillHeaderType.PaymentInformation.ESR }
     * 
     */
    public BillHeaderType.PaymentInformation.ESR createBillHeaderTypePaymentInformationESR() {
        return new BillHeaderType.PaymentInformation.ESR();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link YbInvoiceType }
     * 
     */
    public YbInvoiceType createYbInvoiceType() {
        return new YbInvoiceType();
    }

    /**
     * Create an instance of {@link TaxLineItemType }
     * 
     */
    public TaxLineItemType createTaxLineItemType() {
        return new TaxLineItemType();
    }

    /**
     * Create an instance of {@link BillHeaderType.SenderParty }
     * 
     */
    public BillHeaderType.SenderParty createBillHeaderTypeSenderParty() {
        return new BillHeaderType.SenderParty();
    }

    /**
     * Create an instance of {@link SummaryType.Discount }
     * 
     */
    public SummaryType.Discount createSummaryTypeDiscount() {
        return new SummaryType.Discount();
    }

    /**
     * Create an instance of {@link InstalmentType }
     * 
     */
    public InstalmentType createInstalmentType() {
        return new InstalmentType();
    }

    /**
     * Create an instance of {@link BillType.LineItems }
     * 
     */
    public BillType.LineItems createBillTypeLineItems() {
        return new BillType.LineItems();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link BillHeaderType.PaymentInformation.IBAN }
     * 
     */
    public BillHeaderType.PaymentInformation.IBAN createBillHeaderTypePaymentInformationIBAN() {
        return new BillHeaderType.PaymentInformation.IBAN();
    }

    /**
     * Create an instance of {@link LineItemType }
     * 
     */
    public LineItemType createLineItemType() {
        return new LineItemType();
    }

    /**
     * Create an instance of {@link TaxType }
     * 
     */
    public TaxType createTaxType() {
        return new TaxType();
    }

    /**
     * Create an instance of {@link BillHeaderType.PaymentInformation.Instalments }
     * 
     */
    public BillHeaderType.PaymentInformation.Instalments createBillHeaderTypePaymentInformationInstalments() {
        return new BillHeaderType.PaymentInformation.Instalments();
    }

    /**
     * Create an instance of {@link TaxDetailType }
     * 
     */
    public TaxDetailType createTaxDetailType() {
        return new TaxDetailType();
    }

    /**
     * Create an instance of {@link FixedReference }
     * 
     */
    public FixedReference createFixedReference() {
        return new FixedReference();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link BillHeaderType }
     * 
     */
    public BillHeaderType createBillHeaderType() {
        return new BillHeaderType();
    }

    /**
     * Create an instance of {@link AccountAssignmentType }
     * 
     */
    public AccountAssignmentType createAccountAssignmentType() {
        return new AccountAssignmentType();
    }

    /**
     * Create an instance of {@link NetworkType }
     * 
     */
    public NetworkType createNetworkType() {
        return new NetworkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "URLBillDetails", scope = DeliveryType.class)
    public JAXBElement<String> createDeliveryTypeURLBillDetails(String value) {
        return new JAXBElement<String>(_DeliveryTypeURLBillDetails_QNAME, String.class, DeliveryType.class, value);
    }

}
